### ISSUE TITLE
Agree on how to compare KV

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net-lab#109]
Johan and Elena raised concerns with the current implementation we have in .NET to compare Key/value objects.
Make sure we agree on something for all languages, and implement that.

**Comment by johanste** [comment]
My observation is that while you know that something has changed on the server the etag is different between two requests, the inverse (if the etags are equal, two key/value instances must be equal) is not necessarily true. Any of the mutable values properties have been modified on the client.

**Comment by maririos** [comment]
I see, so something more like:
```
            if (ETags are not null)
            {
                Compare ETag
                Compare LastModified
            }
            // Make sure other fields are still equivalent
            Compare Key
            Compare Label
            Compare Value
            Comapre ContentType
            Compare Locked
            Compare Tags
```

**Comment by maririos** [comment]
FYI @lenala @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
Yeah, given the properties are get/set, I think we need to do full comparison (i.e. all properties). We can optimize the watcher independently by using a custom implementation of the comparison (as in the watcher's case we can assume nobody messes up with the mutable properties).

**Comment by maririos** [comment]
PR created in https://github.com/Azure/azure-sdk-for-net/pull/5242
