### ISSUE TITLE
Make sure we have the right visibility for RequestId 

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net-lab#120]
This issue is tracking getting to the bottom of this comment thread:

https://github.com/Azure/azure-sdk-for-net-lab/pull/111#pullrequestreview-201176682

**Comment by maririos** [comment]
I talked to @drago-draganov offline and he explained to me the different "requestID" there are:
- x-ms-client-request-id => provided by the client. Ability to log it.
- x -ms-request-id =>always set by the server. unique id. Different than the client-request-id
- x-ms-correlation-id => there is no consensus on who generates this. Not relevant for Preview

My PR is focused on `x-ms-client-request-id`. After talking about visibility, he also agrees with @KrzysztofCwalina on making it not public for users. In case we get feedback after preview that users want to set it, we can revisit that approach.

I will start working on the appropriate changes to hide the RequestId.

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-for-net/pull/5294
