### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net-lab#20]
YAML definition has been created and tested. The definition is currently in the public project in Azure DevOps, but when enabling the trigger for PR I'm getting the error : 

`Unable to configure a service on the selected GitHub repository. GitHub returned the error 'Resource not accessible by integration'.`

I validated in the Playground project and I don't get that error and the trigger works fine.
I pinged the Engineer Systems team for help with permissions

**Comment by maririos** [comment]
CI enabled! Will test with next incoming PR to see if trigger is correctly set

**Comment by maririos** [comment]
We are good! Closing!

**Comment by deskev** [comment]
hi Mariana 

I am running into a similar issue trying to set up a trigger on the release pipeline. Do you mind posting what was the solution that fixed your problem? thanks

**Comment by maririos** [comment]
@deskev I don't fully remember, but I believe it was related to permissions.
@danieljurek do you happen to know how to resolve this?

**Comment by deskev** [comment]
@maririos  thanks - just worked with the security team on it - apparently my personal user access token with which I had connected GitHub and Release Project - wasn't set up for Org Wide webhooks. All we had to do was to get a PAT with a higher level access profile.
