### ISSUE TITLE
Support Correlation IDs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#30]
We need the ability to correlate multiple requests that are part of a larger logical operation. For example, all Get requests that are part of a single polling interval in the ConfigurationWatcher

**Comment by maririos** [comment]
Per our conversation, moving the issue out of Preview 1

**Comment by maririos** [comment]
Notes from meeting with service team:
-	Can flow into the service (as the service is a middleware) 
-	Correlation ID is cross service

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5381](https://github.com/Azure/azure-sdk-for-net/issues/5381) via [**ZenHub**](https://www.zenhub.com/)
