### ISSUE TITLE
Support Request ID

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#31]
We should accept user-provided request Id and pass it on to the service. This will be useful to track down specific request particularly in the multi-tier service scenario.

The service is using x-ms-client-request-id header for this.

**Comment by maririos** [comment]
More notes after meeting with Zhenlan and Drago:
-	Customers sends request id (customer controlled) in the header – for retries, we should use the same request id.
-	If the user does not specify a request id, the SDK will generate one.
o	The server will generate one if none is generated it from the SDK and send it back to the client
-	It should surface on error or success cases (for logging or error handling)
o	The information should contain the request ID
-	Do we want to control how the user generates the request id? 
o	We want a way to have sufficient entropy in the id.
o	Right now we are using a GUID in the SDK
-	On storage the GUID returned has information about who handled the specific request.
