### ISSUE TITLE
Review AppConfigService Spec to make sure we implement it fully

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#35]
https://msazure.visualstudio.com/Azure%20AppConfig/_git/AppConfigService?path=%2Fdocs%2Fprotocol&version=GBmaster

This is just a review workitem. If discrepancies between implementation and the spec are discovered, please just file issues to close the gaps.

**Comment by maririos** [comment]
Issues have been created for the individual work we need to do to close the gap.
