### ISSUE TITLE
Azure.Core Cleanup

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#38]
- [x] move types into their own files names appropriately

Pri 1
  - [x] Azure.Core\Buffers\StreamMemoryExtensions.cs(82): // TODO (pri 1) : implement
  - [x] Azure.Core\Net\Pipeline\HttpPipelineTransport.cs(132): // TODO (pri 1) : is it ok to just call .Result here?
  - [x] Azure.Core\Net\Pipeline\HttpPipelineTransport.cs(71): // TODO (pri 1) : any other headers must be added to content?
  - [ ] Azure.Core\Net\Pipeline\LoggingPolicy.cs(22): // TODO (pri 1) : we should remove sensitive information, e.g. keys
  - [x] Azure.Core\Net\PipelineCallContext.cs(24): // TODO (pri 1) : what happens if this is called after AddHeader? Especially for SocketTransport
  - [x] Azure.Core\Net\PipelineContent.cs(21): // TODO (pri 1) : should this support cancellations
  - [x] Azure.Core.Tests\SocketTransport\SocketClientTransport.cs(101): // TODO (pri 1) : this needs to use a real pool and take the connection out, as of now it's very not thread safe

Pri 2
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(12): // TODO (pri 2) : make the type internal
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(30): // TODO (pri 2) : this logs just the URI. We need more
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(47): // TODO (pri 2) : there are more attribute properties we might want to set
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(51): // TODO (pri 2) : is EventKeywords.None ok?
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(8): // TODO (pri 2) : we should log correction/activity
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(9): // TODO (pri 2) : we should log exceptions
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(93): // TODO (pri 2) : should this filter some information?
  - [x] Azure.Core\Diagnostics\ServiceLogger.cs(94): // TODO (pri 2) : should this be more structured?
  - [x] Azure.Core\Net\ClientPipeline.cs(16): // TODO (pri 2) : what are the default status codes to retry?
  - [x] Azure.Core\Net\Pipeline\HttpPipelineTransport.cs(15): // TODO (pri 2) : implement chunked encoding
  - [ ] Azure.Core\OptionsStore.cs(12): // TODO (pri 2) : test that these don't get created when options are read/get, but not set.
  - [x] Azure.Core.Tests\PipelineTests.cs(13): // TODO (pri 2) : Do use the EventRegister NuGet package or the standalone eventRegister.exe tool, to run build-time validation of the event source classes defined in your assemblies.
  - [x] Azure.Core.Tests\SocketTransport\Sequence.cs(146): // TODO (pri 2) : this is a very inneficient implementation.

Pri 3
  - [ ] Azure.Core\Diagnostics\ServiceLogger.cs(16): // TODO (pri 3) : do we want the same source name for all SDk components?
  - [x] Azure.Core\Net\ClientPipeline.cs(30): // TODO (pri 3) : I am not sure this should be here. Maybe we need one per service, as they have different retry policies
  - [x] Azure.Core\Net\Header.cs(152): // TODO (pri 3) : eliminate this allocations
  - [x] Azure.Core\Net\Header.cs(155): // TODO (pri 3) : eliminate this allocations
  - [x] Azure.Core\Net\Header.cs(164): // TODO (pri 3) : eliminate this allocations
  - [x] Azure.Core\Net\Header.cs(171): // TODO (pri 3) : eliminate this allocations
  - [x] Azure.Core\Net\Pipeline\LoggingPolicy.cs(18): // TODO (pri 3) : should this be a true singleton?
  - [x] Azure.Core\Net\PipelineOptions.cs(54): // TODO (pri 3) : I am not happy with the design that needs a semtinel policy. 
  - [ ] Azure.Core\OptionsStore.cs(11): // TODO (pri 3) : optimize the dictionaries
  - [x] Azure.Core.Tests\SocketTransport\Http.cs(13): // TODO (pri 3) : use real HTTP Parser (but it's in corfxlab)
  - [x] Azure.Core.Tests\SocketTransport\SocketClientTransport.cs(34): // TODO (pri 3) : refactor connection cache and GC it.

**Comment by pakrym** [comment]
Closing this as most TODOs were fixed.
