### ISSUE TITLE
Azure.ApplicationModel.Configuration Cleanup

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#39]
- [ ] remove all NotImplementedException
- [ ] remove all TODOs
- [ ] move types into their own files names appropriately

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5395](https://github.com/Azure/azure-sdk-for-net/issues/5395) via [**ZenHub**](https://www.zenhub.com/)
