### ISSUE TITLE
Improve Test Coverage for Azure.ApplicationModel.Configuration

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#41]
For example, we have no tests for Tags, filtering, etc.

**Comment by maririos** [comment]
Issues created:
- Tags: #93 
- Fields: #92

**Comment by maririos** [comment]
@KrzysztofCwalina  could you elaborate more on what do you mean by test for filtering?

**Comment by KrzysztofCwalina** [comment]
I meant If-Match or If-None-Match headers. I think you added these tests and now we have them.

**Comment by maririos** [comment]
Yeah, I thought about implementing the filtering ones, but for us, it is just passing a string with special characters and in some ways, we are already passing `*`. Do we need to explore more of those tests?

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5384](https://github.com/Azure/azure-sdk-for-net/issues/5384) via [**ZenHub**](https://www.zenhub.com/)
