### ISSUE TITLE
Add Configuration Service Samples

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#43]
- [x] Hello World
- [x] Watcher
- [x] Diagnose Logs (in progress)
- [ ] Filtering
- [ ] Batching
- [ ] Locking
- [ ] Revisions
- [x] Retry

**Comment by maririos** [comment]
For the remaining samples, could we just add a link to the Live tests we have?
i.e.
Revisions: https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/Azure.ApplicationModel.Configuration/data-plane/Azure.Configuration.Tests/ConfigurationLiveTests.cs#L405

**Comment by maririos** [comment]
PR https://github.com/Azure/azure-sdk-for-net/pull/5304

**Comment by KrzysztofCwalina** [comment]
I think for pre-release, reusing tests is fine. But for GA, we should have specially written samples. Tests are meant to test and often obscure the main point of a sample or/and do things differently than what people should do in an app.

**Comment by maririos** [comment]
I see. Thanks for the clarification. I will work on the samples, so we finish that the right way, and if something urgent comes, I will leave it as it is

**Comment by maririos** [comment]
More work came up, so we are going to leave this issue as it is for Preview. 
Issue https://github.com/Azure/azure-sdk-for-net-lab/issues/127 will target the work needed for GA.
