### ISSUE TITLE
ConfigurationWatcher Should Allow Adding Keys To Watch

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#50]
ConfigurationWatcher should sllow sdding keys to watch while it's running. Same with stopping to watch.

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5390](https://github.com/Azure/azure-sdk-for-net/issues/5390) via [**ZenHub**](https://www.zenhub.com/)
