### ISSUE TITLE
Decide on Design Issues Azure.ApplicationModel.Configuration

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#52]
- [ ] Should we use Nullable<T> in ConfigurationSetting? For example LastModified DateTime.
- [ ] Should we use nullable reference types  in ConfigurationSetting?
- [ ] Is it OK for ConfigurationSetting.Tags to be IDictionary`2?
- [ ] Can SettingBatch.NextIndex be automatically set while batching?
- [x] Should ConfigurationSetting be a struct?
- [ ] What are we going to do when we want to add new parameters to service methods?

**Comment by KrzysztofCwalina** [comment]
- Should ConfigurationSetting be a struct?
I think we should leave it as a class. It's very large (lots of fields) and the main reason to make it a struct would be to store many of these in a batch more efficiently. But I think we can do it with specialized batch lazy parser.

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5393](https://github.com/Azure/azure-sdk-for-net/issues/5393) via [**ZenHub**](https://www.zenhub.com/)
