### ISSUE TITLE
Describe Contract for Pipeline Abstractions

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net-lab#54]
Decide on the contract for some pipeline APIs:

•	What happened when Context.SetRequestLine is called multiple times?
•	What happened when Context.SetContent is called multiple times?
•	Can SetRequestLine be called after AddHeader?

**Comment by AlexGhiondea** [comment]
[triage] We believe this was already covered during implementation and testing.
