### ISSUE TITLE
Ensure that we have XML doc comments for public APIs

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net-lab#76]

**Comment by maririos** [comment]
@AlexGhiondea could you clarify what you mean with XML doc comments?

**Comment by maririos** [comment]
Issue moved to [Azure/azure-sdk-for-net #5382](https://github.com/Azure/azure-sdk-for-net/issues/5382) via [**ZenHub**](https://www.zenhub.com/)
