### ISSUE TITLE
[Flaky Test] ConfigurationWatcherTests.Helpers

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net-lab#85]
The test ConfigurationWatcherTests.Helpers may be flaky.  It failed on Linux in one build, but passed on Mac and Windows in the same build, and also passed on Linux in the next build.

```
Failed Helpers
Error Message:
Expected: 2
But was: 1
```

Please investigate the root cause and mitigations.

# Failing Builds
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3140

**Comment by maririos** [comment]
I've only seen this test fail for this particular build. I'll keep an eye on it for another week and if it keeps passing I'll close this issue

**Comment by mikeharder** [comment]
I'm fine closing this now.  Here's the recent test history:

![image](https://user-images.githubusercontent.com/9459391/52439705-1330af80-2ad1-11e9-864c-e080eccf0f76.png)

First, be aware the dates in the chart are backwards.  The newest builds are on the left and the oldest builds are on the right (despite the x-axis labels saying the opposite).

The two real failures are the red bars on the far right (representing Jan 24).  The three failures near the middle were massive test failures caused by expired credentials.  So the test hasn't failed in a meaningful way since Jan 24.
